sudo: false
dist: trusty
language: python
python:
  - '3.4'
  - '3.5'
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
script:
  - coverage run --source=scraper ./run_tests.py
after_success:
  - coveralls
